In [146]:
import numpy as np
import pandas as pd

In [147]:
data={"name":["Bill","Tom","Tim","John","Alex","Vanessa","Kate"],      
      "score":[90,80,85,75,95,60,65],      
      "sport":["Wrestling","Football","Skiing","Swimming","Tennis",
               "Karete","Surfing"],      
      "sex":["M","M","M","M","F","F","F"]}
df = pd.DataFrame(data, columns=["sport", "sex"])
df

       sport sex
0  Wrestling   M
1   Football   M
2     Skiing   M
3   Swimming   M
4     Tennis   F
5     Karete   F
6    Surfing   F

In [148]:
df = pd.DataFrame(data)
df

      name  score      sport sex
0     Bill     90  Wrestling   M
1      Tom     80   Football   M
2      Tim     85     Skiing   M
3     John     75   Swimming   M
4     Alex     95     Tennis   F
5  Vanessa     60     Karete   F
6     Kate     65    Surfing   F

In [149]:
df.index, df.columns

(RangeIndex(start=0, stop=7, step=1),
 Index(['name', 'score', 'sport', 'sex'], dtype='object'))

In [150]:
df[["name", "score"]]

      name  score
0     Bill     90
1      Tom     80
2      Tim     85
3     John     75
4     Alex     95
5  Vanessa     60
6     Kate     65

In [151]:
df.loc[0]

name          Bill
score           90
sport    Wrestling
sex              M
Name: 0, dtype: object

In [152]:
df.iloc[0]

name          Bill
score           90
sport    Wrestling
sex              M
Name: 0, dtype: object

In [153]:
df

      name  score      sport sex
0     Bill     90  Wrestling   M
1      Tom     80   Football   M
2      Tim     85     Skiing   M
3     John     75   Swimming   M
4     Alex     95     Tennis   F
5  Vanessa     60     Karete   F
6     Kate     65    Surfing   F

In [154]:
df["pass"]=df["score"]>90
df

      name  score      sport sex   pass
0     Bill     90  Wrestling   M  False
1      Tom     80   Football   M  False
2      Tim     85     Skiing   M  False
3     John     75   Swimming   M  False
4     Alex     95     Tennis   F   True
5  Vanessa     60     Karete   F  False
6     Kate     65    Surfing   F  False

In [155]:
scores={"Math":{"A":85,"B":90,"C":95}, "Physics":{"A":90,"B":80,"C":75}}

In [156]:
df = pd.DataFrame(scores)
df

   Math  Physics
A    85       90
B    90       80
C    95       75

In [157]:
df.T

          A   B   C
Math     85  90  95
Physics  90  80  75

In [158]:
df

   Math  Physics
A    85       90
B    90       80
C    95       75

In [159]:
obj=pd.Series(np.arange(5),
              index=["a","b","c","d","e"])

In [160]:
obj["a"]

np.int64(0)

In [161]:
obj[0:3]

a    0
b    1
c    2
dtype: int64

In [162]:
obj[[0, 2]]

C:\Users\Vigna\AppData\Local\Temp\ipykernel_188680\2723722654.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[0, 2]]

a    0
c    2
dtype: int64

In [163]:
data=pd.DataFrame(
    np.arange(16).reshape(4,4),
    index=["London","Paris",
           "Berlin","Istanbul"],
    columns=["one","two","three","four"])
data

          one  two  three  four
London      0    1      2     3
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [164]:
data.iloc[0:2]

        one  two  three  four
London    0    1      2     3
Paris     4    5      6     7

In [165]:
data.loc[["London", "Istanbul"]]

          one  two  three  four
London      0    1      2     3
Istanbul   12   13     14    15

In [166]:
data.iloc[[0,2]]

        one  two  three  four
London    0    1      2     3
Berlin    8    9     10    11

In [167]:
data["four"]>5

London      False
Paris        True
Berlin       True
Istanbul     True
Name: four, dtype: bool

In [168]:
data[data["four"]>5]

          one  two  three  four
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [169]:
data

          one  two  three  four
London      0    1      2     3
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [170]:
data.iloc[[0,1],[2,3]]

        three  four
London      2     3
Paris       6     7

In [171]:
data

          one  two  three  four
London      0    1      2     3
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [172]:
{"London":"L","Paris":"P"}

{'London': 'L', 'Paris': 'P'}

In [173]:
d2 = data.reindex({"London":"L","Paris":"P"})
d2

        one  two  three  four
London    0    1      2     3
Paris     4    5      6     7

In [174]:
data

          one  two  three  four
London      0    1      2     3
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [175]:
data

          one  two  three  four
London      0    1      2     3
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [176]:
data.mean(axis=0), data.mean(axis=1)

(one      6.0
 two      7.0
 three    8.0
 four     9.0
 dtype: float64,
 London       1.5
 Paris        5.5
 Berlin       9.5
 Istanbul    13.5
 dtype: float64)

In [177]:
df1=pd.DataFrame(
    np.arange(6).reshape(2,3),
    columns=list("ABC"),
    index=["Tim","Tom"])
df2=pd.DataFrame(
    np.arange(9).reshape(3,3),
    columns=list("ACD"),
    index=["Tim","Kate","Tom"])

df1, df2

(     A  B  C
 Tim  0  1  2
 Tom  3  4  5,
       A  C  D
 Tim   0  1  2
 Kate  3  4  5
 Tom   6  7  8)

In [178]:
df1+df2

        A   B     C   D
Kate  NaN NaN   NaN NaN
Tim   0.0 NaN   3.0 NaN
Tom   9.0 NaN  12.0 NaN

In [179]:
df1.add(df2, fill_value=0)

        A    B     C    D
Kate  3.0  NaN   4.0  5.0
Tim   0.0  1.0   3.0  2.0
Tom   9.0  4.0  12.0  8.0

In [180]:
for i in df1:
    print(i)
    print("-----------")

A
-----------
B
-----------
C
-----------

In [181]:
df=pd.DataFrame(
    np.arange(12).reshape(3,4),
    index=["two","one","three"],
    columns=["d","a","b","c"])
df

       d  a   b   c
two    0  1   2   3
one    4  5   6   7
three  8  9  10  11

In [182]:
df.sort_index()

       d  a   b   c
one    4  5   6   7
three  8  9  10  11
two    0  1   2   3

In [183]:
df.sort_index(axis=1)

       a   b   c  d
two    1   2   3  0
one    5   6   7  4
three  9  10  11  8

In [184]:
df.iloc[0].sort_values()

d    0
a    1
b    2
c    3
Name: two, dtype: int64

In [185]:
df

       d  a   b   c
two    0  1   2   3
one    4  5   6   7
three  8  9  10  11

In [186]:
df2=pd.DataFrame(
    {"a":[5,3,-1,9],"b":[1,-2,0,5]})
df2

   a  b
0  5  1
1  3 -2
2 -1  0
3  9  5

In [187]:
df2.sort_values(by="b")

   a  b
1  3 -2
2 -1  0
0  5  1
3  9  5

In [188]:
df2.sort_values(['a','b'])

   a  b
2 -1  0
1  3 -2
0  5  1
3  9  5

In [189]:
df2["a"].sum()

np.int64(16)

In [190]:
df2

   a  b
0  5  1
1  3 -2
2 -1  0
3  9  5

In [191]:
df2.sum()

a    16
b     4
dtype: int64

In [192]:
df2.sum(axis=1)

0     6
1     1
2    -1
3    14
dtype: int64

In [193]:
df2.mean()

a    4.0
b    1.0
dtype: float64

In [194]:
df2.idxmax()

a    3
b    3
dtype: int64

In [195]:
df2.cumsum()

    a  b
0   5  1
1   8 -1
2   7 -1
3  16  4

In [196]:
df2

   a  b
0  5  1
1  3 -2
2 -1  0
3  9  5

In [197]:
df2.describe()

              a        b
count  4.000000  4.00000
mean   4.000000  1.00000
std    4.163332  2.94392
min   -1.000000 -2.00000
25%    2.000000 -0.50000
50%    4.000000  0.50000
75%    6.000000  2.00000
max    9.000000  5.00000

In [198]:
df2["a"].describe()

count    4.000000
mean     4.000000
std      4.163332
min     -1.000000
25%      2.000000
50%      4.000000
75%      6.000000
max      9.000000
Name: a, dtype: float64

In [199]:
df2

   a  b
0  5  1
1  3 -2
2 -1  0
3  9  5

In [200]:
df2.iloc[0].describe()

count    2.000000
mean     3.000000
std      2.828427
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
Name: 0, dtype: float64

In [201]:
df2.corr()

        a       b
a  1.0000  0.7615
b  0.7615  1.0000

In [202]:
df2.cov()

           a         b
a  17.333333  9.333333
b   9.333333  8.666667

In [203]:
import pandas as pd
import numpy as np

df = pd.DataFrame([
    [1, 2, 3],
    [4, np.nan, 5],
    [np.nan, np.nan, np.nan]
])
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

In [204]:
df.isnull()

       0      1      2
0  False  False  False
1  False   True  False
2   True   True   True

In [205]:
df.notnull()

       0      1      2
0   True   True   True
1   True  False   True
2  False  False  False

In [206]:
df.dropna()

     0    1    2
0  1.0  2.0  3.0

In [207]:
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

In [208]:
df.loc[df[2].dropna().index]

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0

In [209]:
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

In [210]:
df.fillna(0)

     0    1    2
0  1.0  2.0  3.0
1  4.0  0.0  5.0
2  0.0  0.0  0.0

In [211]:
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

In [212]:
df.fillna(method='ffill')

C:\Users\Vigna\AppData\Local\Temp\ipykernel_188680\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     0    1    2
0  1.0  2.0  3.0
1  4.0  2.0  5.0
2  4.0  2.0  5.0

In [213]:
data=pd.DataFrame({"a":["one","two"]*3,
                   "b":[1,1,2,3,2,3]})
data

     a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [214]:
data.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [215]:
data.drop_duplicates()

     a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [216]:
data

     a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [217]:
data["c"]=range(6)

In [218]:
data

     a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [219]:
d1=pd.DataFrame(
    {"key":["a","b","c","c","d","e"],
     "num1":range(6)})
d2=pd.DataFrame(
    {"key":["b","c","e","f"],
     "num2":range(4)})

In [220]:
d1, d2

(  key  num1
 0   a     0
 1   b     1
 2   c     2
 3   c     3
 4   d     4
 5   e     5,
   key  num2
 0   b     0
 1   c     1
 2   e     2
 3   f     3)

In [221]:
pd.merge(d1, d2)

  key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [222]:
pd.merge(d1, d2, on='key')

  key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [223]:
d3=pd.DataFrame(
    {"key1":["a","b","c","c","d","e"],
     "num1":range(6)})
d4=pd.DataFrame(
    {"key2":["b","c","e","f"],
     "num2":range(4)})

In [224]:
mg = pd.merge(d3, d4, left_on="key1", right_on="key2", how="left")

In [225]:
mg

  key1  num1 key2  num2
0    a     0  NaN   NaN
1    b     1    b   0.0
2    c     2    c   1.0
3    c     3    c   1.0
4    d     4  NaN   NaN
5    e     5    e   2.0

In [226]:
mg.loc[mg.index.max()+1]=[1,2,3,4]
mg

  key1  num1 key2  num2
0    a     0  NaN   NaN
1    b     1    b   0.0
2    c     2    c   1.0
3    c     3    c   1.0
4    d     4  NaN   NaN
5    e     5    e   2.0
6    1     2    3   4.0

In [243]:
df = pd.DataFrame(np.arange(16).reshape(4,4), index=[["a","a","b","b"],[1,2,3,4]])

In [244]:
df

      0   1   2   3
a 1   0   1   2   3
  2   4   5   6   7
b 3   8   9  10  11
  4  12  13  14  15

In [245]:
df.index.names=("qwert","qwsa")

In [242]:
df

             0   1   2   3
qwert qwsa
a     1      0   1   2   3
      2      4   5   6   7
b     3      8   9  10  11
      4     12  13  14  15

In [247]:
df[0]

qwert  qwsa
a      1        0
       2        4
b      3        8
       4       12
Name: 0, dtype: int64

In [250]:
a = df.reset_index()
a["qwert"]

0    a
1    a
2    b
3    b
Name: qwert, dtype: object

In [251]:
df=pd.DataFrame(
    {"key1":list("aabbab"),
     "key2":["one","two","three"]*2,
     "data1":np.random.randn(6),
     "data2":np.random.randn(6)})
df

  key1   key2     data1     data2
0    a    one  1.065961  3.642784
1    a    two  0.640862  0.533299
2    b  three  2.426923  0.580049
3    b    one -0.052368 -0.243670
4    a    two -1.427014  0.144511
5    b  three -0.138524 -0.762870

In [252]:
for name, grp in df.groupby("key1"):
    print(name)

a
b

In [253]:
for name, grp in df.groupby("key1"):
    print(grp)

  key1 key2     data1     data2
0    a  one  1.065961  3.642784
1    a  two  0.640862  0.533299
4    a  two -1.427014  0.144511
  key1   key2     data1     data2
2    b  three  2.426923  0.580049
3    b    one -0.052368 -0.243670
5    b  three -0.138524 -0.762870

In [255]:
for name, grp in df.groupby("key1"):
    print(grp["data1"].mean(), grp["data1"].max(), grp["data1"].idxmax())

0.09326983012816041 1.0659614910874347 0
0.7453437259803346 2.426922819935438 2

In [264]:
arr = np.linspace(22,23,16).reshape(4,4)

In [268]:
arr = np.random.rand(4,4)

In [271]:
arr

array([[0.45519881, 0.39696736, 0.34396807, 0.40027863],
       [0.71675665, 0.18948152, 0.02286885, 0.04406424],
       [0.24700515, 0.20394362, 0.45527178, 0.24468834],
       [0.80757482, 0.46368469, 0.06793989, 0.57348076]])

In [ ]:
np.linalg.inv(arr)

array([[-2.96859336,  1.33507067,  2.00984999,  1.11189213],
       [12.73133256,  0.7846906 , -8.88912995, -5.1537748 ],
       [-0.86167742,  0.29432827,  2.93310212, -0.67265412],
       [-6.01139693, -2.54937079,  4.00950607,  4.42471764]])

In [272]:
np.linalg.det(arr)

np.float64(-0.012649136376022548)

In [273]:
np.linalg.eig(arr)

EigResult(eigenvalues=array([ 1.45723898+0.j        , -0.19893953+0.j        ,
        0.20756671+0.02341901j,  0.20756671-0.02341901j]), eigenvectors=array([[ 0.53179467+0.j        ,  0.47114713+0.j        ,
         0.05349888+0.01168304j,  0.05349888-0.01168304j],
       [ 0.33118327+0.j        , -0.8774777 +0.j        ,
         0.49013476-0.07225239j,  0.49013476+0.07225239j],
       [ 0.36649639+0.j        ,  0.08570003+0.j        ,
         0.32555234+0.0786167j ,  0.32555234-0.0786167j ],
       [ 0.68788987+0.j        ,  0.02662277+0.j        ,
        -0.79961489+0.j        , -0.79961489-0.j        ]]))

In [283]:
arr = np.random.randint(0,100, (2,3))

In [284]:
arr

array([[53, 18,  7],
       [ 3, 79, 39]], dtype=int32)